// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdynuhmugrsoggwqjyik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkeW51aG11Z3Jzb2dnd3FqeWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk5NDkzNzcsImV4cCI6MjA0NTUyNTM3N30.UgdY7RpOdEqU0Jr6C0lNlvp7PYTABS9B29q15UYBZMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);